namespace SmartHomeAutomation.Models;

/// <summary>
/// Represents an event generated by a device.
/// </summary>
public class DeviceEvent
{
    /// <summary>
    /// Unique identifier for the event.
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// Identifier of the device that generated the event.
    /// </summary>
    public string DeviceId { get; set; }

    /// <summary>
    /// Temperature recorded by the device.
    /// </summary>
    public float Temperature { get; set; }

    /// <summary>
    /// Humidity recorded by the device.
    /// </summary>
    public float Humidity { get; set; }

    /// <summary>
    /// Timestamp of the event.
    /// </summary>
    public DateTime Timestamp { get; set; }
}